version: '3.8'
services:
  uploader:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: uploader
    expose:
      - ${SERVER_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - '.env'
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped
